[project]
name = "analise-comentarios-ifood"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-google-genai>=3.1.0",
    "python-dotenv>=1.2.1",
    "streamlit>=1.51.0",
]
